# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-05 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassPercentage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_index',
            field=models.IntegerField(default=1),
        ),
    ]
