# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-30 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PassPercentage', '0002_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='name',
            new_name='your_name',
        ),
    ]
