# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-06 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PassPercentage', '0002_comment_comment_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_title',
        ),
    ]
