# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-30 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassPercentage', '0003_auto_20171130_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='your_name_slug',
            field=models.SlugField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='name',
            name='your_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
